/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
    const mesh = useRef();
    const group = useRef();
    const { nodes, materials } = useGLTF("/nosepass.glb");
    useFrame(() => (mesh.current.rotation.y += 1 / 100));
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                ref={mesh}
                castShadow
                receiveShadow
                geometry={nodes.mesh_0.geometry}
                material={nodes.mesh_0.material}
            />
        </group>
    );
}

useGLTF.preload("/nosepass.glb");
